### ISSUE TITLE
AssertionError: pkg.whl is not compatible with this platform

### ISSUE THREAD

**Issue by FlorianWilhelm** [dairiki/humpty#2]
First of all, great tool! I am trying to use it with `numpy-1.12.1-cp35-cp35m-manylinux1_x86_64.whl` but I get
```
AssertionError: numpy-1.12.1-cp35-cp35m-manylinux1_x86_64.whl is not compatible with this platform
```
The problem is the assertion check `assert wheel.is_compatible()` in `EggWriter` since it works if I just comment it. I think `is_compatible()` is actually quite selective. I have architecture `cp35m-x86_64-linux-gnu` while the wheel is `manylinux1_x86_64` so it is actually compatible but fails anyway. My suggestion would be to add a command line flag that avoids the check for compatibility. I could even provide a PR if you agree.

**Comment by dairiki** [comment]
I think the issues is that distlib's ``is_compatible`` is broken under python 3.5 and python 3.6. 
 See [distlib #93](https://bitbucket.org/pypa/distlib/issues/93).

For now, I've converted the assert to a warning (b365925).  This is included in today's release of humpty 0.2.
